### ISSUE TITLE
我似乎没有找到“资源/BiliLinkerRevise.jar”？

### ISSUE THREAD

**Issue by Glucy-2** [KJZH001/BiliLinkerRevise#1]

**Comment by KJZH001** [comment]
抱歉，这是由于我的疏忽导致的问题
现在已经补上了，你可以在仓库的资源文件夹中或者releases中下载编译成品的jar
如果你在运行过程中没有遇到问题的话那么您可以选择关闭这个issue了

**Comment by Glucy-2** [comment]
正常使用，没有问题😄
