### ISSUE TITLE
似乎发送的图片会加载不出来

### ISSUE THREAD

**Issue by howrain** [KJZH001/BiliLinkerRevise#2]
![image](https://user-images.githubusercontent.com/29175296/92317102-6f521180-f02f-11ea-9ce4-532652382852.png)
类似于这样

**Comment by howrain** [comment]
重新看了下  只有私聊的情况会出现这样

**Comment by KJZH001** [comment]
> 重新看了下 只有私聊的情况会出现这样

由于这部分是直接用原作者写的插件代码，所以我也不是很清楚
你可以把日志发上来，我会尝试性的解决一下这个问题[但不保证一定能解决]
而且我也真的没有想到这个插件会有人私聊用 (汗= =) [仅此而已，没别的意思]

**Comment by howrain** [comment]
好吧 也没什么影像，测试的时候发现的，确实没人私聊用(233
